### PR TITLE
gui can be disabled

### PR DESCRIPTION
**Pull request by blackvladimir**
in server instalation we doesn't need gui.

### CODE REVIEW

**Comment by l-korous** [comment]
Ahoj,

ma tohle znamenat ze bych nemel dostavat hlasky typu: "ImportError:
libGLEW.so.1.6: cannot open shared object file: No such file or directory"?

Nebo to prestane az kdyz setnu NO_GLUT v hermesu?

Lukas

On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
reply@reply.github.com

> wrote:
> 
> in server instalation we doesn't need gui.
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/blackvladimir/hermes-python master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/hpfem/hermes-python/pull/24
> 
> -- Commit Summary --
> - gui can be disabled
> 
> -- File Changes --
> 
> A config.pxi (1)
> M hermes2d/hermes2d.pxd (21)
> M hermes2d/hermes2d.pyx (22)
> M hermes2d/setup.py (1)
> 
> -- Patch Links --
> 
>  https://github.com/hpfem/hermes-python/pull/24.patch
>  https://github.com/hpfem/hermes-python/pull/24.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24

## 

_Lukas Korous_

**Comment by blackvladimir** [comment]
Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.

v Hermesu v CMake.vars

set(H2D_WITH_GLUT NO)

a ve wraperech v config.pxi

DEF GUI = False

Vlada

On Wed, 15 Feb 2012 19:00:16 +0100, l-korous  
reply@reply.github.com  
wrote:

**Comment by l-korous** [comment]
OK, no ja jsem ted tedy nainstaloval do pythonroot.tar.gz na truckee hermes
s
set(H2D_WITH_GLUT NO) a wrappery s DEF GUI = False
a stejne dostavam tu chybu.

A dal jsem si praci zjistit proc - je to tim, ze se bere hermes ze systemu
(z femhubu) a nikoliv z pythonroot.tar.gz.

Jak to overit:
- worksheet se mi evaluoval na lenovu (myslim ze kdyz jsem updatoval nclab,
  tak to byla jedina noda, kde update prosel uspesne, to jen rikam kdybys na
  to narazil)
- no a kdyz jsem tu hlasku
  "ImportError: libGLEW.so.1.6: cannot open shared object file: No such file
  or
  directory"
  dostal, tak jsem pokusne smazal hermes z femhubu na lenovu, a dostal jsem
  hlasku o chybejicim hermesu.

Lukas

On Thu, Feb 16, 2012 at 10:23 AM, blackvladimir <
reply@reply.github.com

> wrote:
> 
> Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.
> 
> v Hermesu v CMake.vars
> 
> set(H2D_WITH_GLUT NO)
> 
> a ve wraperech v config.pxi
> 
> DEF GUI = False
> 
> Vlada
> 
> On Wed, 15 Feb 2012 19:00:16 +0100, l-korous
> reply@reply.github.com
> wrote:
> 
> > Ahoj,
> > 
> > ma tohle znamenat ze bych nemel dostavat hlasky typu: "ImportError:
> > libGLEW.so.1.6: cannot open shared object file: No such file or
> > directory"?
> > 
> > Nebo to prestane az kdyz setnu NO_GLUT v hermesu?
> > 
> > Lukas
> > 
> > On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > in server instalation we doesn't need gui.
> > > 
> > > You can merge this Pull Request by running:
> > > 
> > >  git pull https://github.com/blackvladimir/hermes-python master
> > > 
> > > Or you can view, comment on it, or merge it online at:
> > > 
> > >  https://github.com/hpfem/hermes-python/pull/24
> > > 
> > > -- Commit Summary --
> > > - gui can be disabled
> > > 
> > > -- File Changes --
> > > 
> > > A config.pxi (1)
> > > M hermes2d/hermes2d.pxd (21)
> > > M hermes2d/hermes2d.pyx (22)
> > > M hermes2d/setup.py (1)
> > > 
> > > -- Patch Links --
> > > 
> > >  https://github.com/hpfem/hermes-python/pull/24.patch
> > >  https://github.com/hpfem/hermes-python/pull/24.diff
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hpfem/hermes-python/pull/24
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24#issuecomment-3997422

## 

_Lukas Korous_

**Comment by blackvladimir** [comment]
Tak to ale znamena ze je neco uplne spatne protoze engine nema co sahat do  
systemu. Podivam se na to

On Thu, 16 Feb 2012 18:00:22 +0100, l-korous  
reply@reply.github.com  
wrote:

**Comment by l-korous** [comment]
OK,

jeste abych tu hlasku co jsem dostal o chybejicim hermesu rozvinul, byla to
hlaska o chybejici C++ knihovne kterou jsem smazal z
/home/lab/repo/git/femhub-distribution/local/lib.

Import hermes2d prosel, ale nevim jaky hermes2d to vlastne byl jen vim ze
ne ten v pythonroot.tar.gz.

L

On Thu, Feb 16, 2012 at 6:03 PM, blackvladimir <
reply@reply.github.com

> wrote:
> 
> Tak to ale znamena ze je neco uplne spatne protoze engine nema co sahat do
> systemu. Podivam se na to
> 
> On Thu, 16 Feb 2012 18:00:22 +0100, l-korous
> reply@reply.github.com
> wrote:
> 
> > OK, no ja jsem ted tedy nainstaloval do pythonroot.tar.gz na truckee
> > hermes
> > s
> > set(H2D_WITH_GLUT NO) a wrappery s DEF GUI = False
> > a stejne dostavam tu chybu.
> > 
> > A dal jsem si praci zjistit proc - je to tim, ze se bere hermes ze
> > systemu
> > (z femhubu) a nikoliv z pythonroot.tar.gz.
> > 
> > Jak to overit:
> > - worksheet se mi evaluoval na lenovu (myslim ze kdyz jsem updatoval
> >   nclab,
> >   tak to byla jedina noda, kde update prosel uspesne, to jen rikam kdybys
> >   na
> >   to narazil)
> > - no a kdyz jsem tu hlasku
> >   "ImportError: libGLEW.so.1.6: cannot open shared object file: No such
> >   file
> >   or
> >   directory"
> >   dostal, tak jsem pokusne smazal hermes z femhubu na lenovu, a dostal jsem
> >   hlasku o chybejicim hermesu.
> > 
> > Lukas
> > 
> > On Thu, Feb 16, 2012 at 10:23 AM, blackvladimir <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.
> > > 
> > > v Hermesu v CMake.vars
> > > 
> > > set(H2D_WITH_GLUT NO)
> > > 
> > > a ve wraperech v config.pxi
> > > 
> > > DEF GUI = False
> > > 
> > > Vlada
> > > 
> > > On Wed, 15 Feb 2012 19:00:16 +0100, l-korous
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > Ahoj,
> > > > 
> > > > ma tohle znamenat ze bych nemel dostavat hlasky typu: "ImportError:
> > > > libGLEW.so.1.6: cannot open shared object file: No such file or
> > > > directory"?
> > > > 
> > > > Nebo to prestane az kdyz setnu NO_GLUT v hermesu?
> > > > 
> > > > Lukas
> > > > 
> > > > On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > in server instalation we doesn't need gui.
> > > > > 
> > > > > You can merge this Pull Request by running:
> > > > > 
> > > > >  git pull https://github.com/blackvladimir/hermes-python master
> > > > > 
> > > > > Or you can view, comment on it, or merge it online at:
> > > > > 
> > > > >  https://github.com/hpfem/hermes-python/pull/24
> > > > > 
> > > > > -- Commit Summary --
> > > > > - gui can be disabled
> > > > > 
> > > > > -- File Changes --
> > > > > 
> > > > > A config.pxi (1)
> > > > > M hermes2d/hermes2d.pxd (21)
> > > > > M hermes2d/hermes2d.pyx (22)
> > > > > M hermes2d/setup.py (1)
> > > > > 
> > > > > -- Patch Links --
> > > > > 
> > > > >  https://github.com/hpfem/hermes-python/pull/24.patch
> > > > >  https://github.com/hpfem/hermes-python/pull/24.diff
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/hpfem/hermes-python/pull/24
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-3997422
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24#issuecomment-4004694

## 

_Lukas Korous_

**Comment by blackvladimir** [comment]
Aha on nekdo vypnul na nodech zabezpeceni pythonu. Nevim jaky mel k tomu  
duvod.

On Thu, 16 Feb 2012 18:00:22 +0100, l-korous  
reply@reply.github.com  
wrote:

**Comment by l-korous** [comment]
Ja jsem mimo podezreni, protoze ani nevim jak bych to udelal :).

OK, muzes to poladit a overit tedy jestli jsem spravne nainstaloval hermes
& wrappery do pythonroot.tar.gz, ze se to importne?

L

On Thu, Feb 16, 2012 at 6:09 PM, blackvladimir <
reply@reply.github.com

> wrote:
> 
> Aha on nekdo vypnul na nodech zabezpeceni pythonu. Nevim jaky mel k tomu
> duvod.
> 
> On Thu, 16 Feb 2012 18:00:22 +0100, l-korous
> reply@reply.github.com
> wrote:
> 
> > OK, no ja jsem ted tedy nainstaloval do pythonroot.tar.gz na truckee
> > hermes
> > s
> > set(H2D_WITH_GLUT NO) a wrappery s DEF GUI = False
> > a stejne dostavam tu chybu.
> > 
> > A dal jsem si praci zjistit proc - je to tim, ze se bere hermes ze
> > systemu
> > (z femhubu) a nikoliv z pythonroot.tar.gz.
> > 
> > Jak to overit:
> > - worksheet se mi evaluoval na lenovu (myslim ze kdyz jsem updatoval
> >   nclab,
> >   tak to byla jedina noda, kde update prosel uspesne, to jen rikam kdybys
> >   na
> >   to narazil)
> > - no a kdyz jsem tu hlasku
> >   "ImportError: libGLEW.so.1.6: cannot open shared object file: No such
> >   file
> >   or
> >   directory"
> >   dostal, tak jsem pokusne smazal hermes z femhubu na lenovu, a dostal jsem
> >   hlasku o chybejicim hermesu.
> > 
> > Lukas
> > 
> > On Thu, Feb 16, 2012 at 10:23 AM, blackvladimir <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.
> > > 
> > > v Hermesu v CMake.vars
> > > 
> > > set(H2D_WITH_GLUT NO)
> > > 
> > > a ve wraperech v config.pxi
> > > 
> > > DEF GUI = False
> > > 
> > > Vlada
> > > 
> > > On Wed, 15 Feb 2012 19:00:16 +0100, l-korous
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > Ahoj,
> > > > 
> > > > ma tohle znamenat ze bych nemel dostavat hlasky typu: "ImportError:
> > > > libGLEW.so.1.6: cannot open shared object file: No such file or
> > > > directory"?
> > > > 
> > > > Nebo to prestane az kdyz setnu NO_GLUT v hermesu?
> > > > 
> > > > Lukas
> > > > 
> > > > On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > in server instalation we doesn't need gui.
> > > > > 
> > > > > You can merge this Pull Request by running:
> > > > > 
> > > > >  git pull https://github.com/blackvladimir/hermes-python master
> > > > > 
> > > > > Or you can view, comment on it, or merge it online at:
> > > > > 
> > > > >  https://github.com/hpfem/hermes-python/pull/24
> > > > > 
> > > > > -- Commit Summary --
> > > > > - gui can be disabled
> > > > > 
> > > > > -- File Changes --
> > > > > 
> > > > > A config.pxi (1)
> > > > > M hermes2d/hermes2d.pxd (21)
> > > > > M hermes2d/hermes2d.pyx (22)
> > > > > M hermes2d/setup.py (1)
> > > > > 
> > > > > -- Patch Links --
> > > > > 
> > > > >  https://github.com/hpfem/hermes-python/pull/24.patch
> > > > >  https://github.com/hpfem/hermes-python/pull/24.diff
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/hpfem/hermes-python/pull/24
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-3997422
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24#issuecomment-4004832

## 

_Lukas Korous_

**Comment by blackvladimir** [comment]
Tak to vypnul luke kdyz neco testoval. Ja jsem to vratil a funguje to  
akorat hermes_module pouziva grafiku takze nejde importovat. Konretne je  
to PyWinGeom.

Dalsi vec je ze hermes pri calculation testu hazi to jak uz si psal s tim  
ze to neco pise na standartni vystup. Me se to nedari reprodukovat u sebe  
ale muzu to zkusit odladit na truckee.

On Thu, 16 Feb 2012 18:12:41 +0100, l-korous  
reply@reply.github.com  
wrote:

**Comment by l-korous** [comment]
On Thu, Feb 16, 2012 at 7:30 PM, blackvladimir <
reply@reply.github.com

> wrote:
> 
> Tak to vypnul luke kdyz neco testoval. Ja jsem to vratil a funguje to
> akorat hermes_module pouziva grafiku takze nejde importovat. Konretne je
> to PyWinGeom.

Ono je to tim, ze se tam nebere ohled na config.pxi. Nevim proc, ale
vyresil jsem to tak, ze pred "import hermes2d" jsem dal "DEF GUI = False",
moduly stejne nebudou zadne Viewcka nikdy pouzivat. Ted to ladim u sebe,
pak to dam na truckee.

> Dalsi vec je ze hermes pri calculation testu hazi to jak uz si psal s tim
> ze to neco pise na standartni vystup. Me se to nedari reprodukovat u sebe
> ale muzu to zkusit odladit na truckee.

A u Tebe to funguje, jak hermes, tak wrappery aktualni verze?

Lukas

> On Thu, 16 Feb 2012 18:12:41 +0100, l-korous
> reply@reply.github.com
> wrote:
> 
> > Ja jsem mimo podezreni, protoze ani nevim jak bych to udelal :).
> > 
> > OK, muzes to poladit a overit tedy jestli jsem spravne nainstaloval
> > hermes
> > & wrappery do pythonroot.tar.gz, ze se to importne?
> > 
> > L
> > 
> > On Thu, Feb 16, 2012 at 6:09 PM, blackvladimir <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Aha on nekdo vypnul na nodech zabezpeceni pythonu. Nevim jaky mel k tomu
> > > duvod.
> > > 
> > > On Thu, 16 Feb 2012 18:00:22 +0100, l-korous
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > OK, no ja jsem ted tedy nainstaloval do pythonroot.tar.gz na truckee
> > > > hermes
> > > > s
> > > > set(H2D_WITH_GLUT NO) a wrappery s DEF GUI = False
> > > > a stejne dostavam tu chybu.
> > > > 
> > > > A dal jsem si praci zjistit proc - je to tim, ze se bere hermes ze
> > > > systemu
> > > > (z femhubu) a nikoliv z pythonroot.tar.gz.
> > > > 
> > > > Jak to overit:
> > > > - worksheet se mi evaluoval na lenovu (myslim ze kdyz jsem updatoval
> > > >   nclab,
> > > >   tak to byla jedina noda, kde update prosel uspesne, to jen rikam
> > > >   kdybys
> > > >   na
> > > >   to narazil)
> > > > - no a kdyz jsem tu hlasku
> > > >   "ImportError: libGLEW.so.1.6: cannot open shared object file: No such
> > > >   file
> > > >   or
> > > >   directory"
> > > >   dostal, tak jsem pokusne smazal hermes z femhubu na lenovu, a dostal
> > > >   jsem
> > > >   hlasku o chybejicim hermesu.
> > > > 
> > > > Lukas
> > > > 
> > > > On Thu, Feb 16, 2012 at 10:23 AM, blackvladimir <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.
> > > > > 
> > > > > v Hermesu v CMake.vars
> > > > > 
> > > > > set(H2D_WITH_GLUT NO)
> > > > > 
> > > > > a ve wraperech v config.pxi
> > > > > 
> > > > > DEF GUI = False
> > > > > 
> > > > > Vlada
> > > > > 
> > > > > On Wed, 15 Feb 2012 19:00:16 +0100, l-korous
> > > > > reply@reply.github.com
> > > > > wrote:
> > > > > 
> > > > > > Ahoj,
> > > > > > 
> > > > > > ma tohle znamenat ze bych nemel dostavat hlasky typu: "ImportError:
> > > > > > libGLEW.so.1.6: cannot open shared object file: No such file or
> > > > > > directory"?
> > > > > > 
> > > > > > Nebo to prestane az kdyz setnu NO_GLUT v hermesu?
> > > > > > 
> > > > > > Lukas
> > > > > > 
> > > > > > On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
> > > > > > reply@reply.github.com
> > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > in server instalation we doesn't need gui.
> > > > > > > 
> > > > > > > You can merge this Pull Request by running:
> > > > > > > 
> > > > > > >  git pull https://github.com/blackvladimir/hermes-python master
> > > > > > > 
> > > > > > > Or you can view, comment on it, or merge it online at:
> > > > > > > 
> > > > > > >  https://github.com/hpfem/hermes-python/pull/24
> > > > > > > 
> > > > > > > -- Commit Summary --
> > > > > > > - gui can be disabled
> > > > > > > 
> > > > > > > -- File Changes --
> > > > > > > 
> > > > > > > A config.pxi (1)
> > > > > > > M hermes2d/hermes2d.pxd (21)
> > > > > > > M hermes2d/hermes2d.pyx (22)
> > > > > > > M hermes2d/setup.py (1)
> > > > > > > 
> > > > > > > -- Patch Links --
> > > > > > > 
> > > > > > >  https://github.com/hpfem/hermes-python/pull/24.patch
> > > > > > >  https://github.com/hpfem/hermes-python/pull/24.diff
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > https://github.com/hpfem/hermes-python/pull/24
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-3997422
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-4004832
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24#issuecomment-4006352

## 

_Lukas Korous_

**Comment by blackvladimir** [comment]
ono je treba to config.pxi includovat jak na zacatku hlavniho pxd souboru  
tak na zacatku pyx souboru.

ad "This engine tried to send data to standard output, and therefore it  
was terminated." Zjistil jsem ze to dela xml parser, kdyz je v xml nejaka  
chyba tak ji vypise na standartni chybovy vystup. Reseni je dvoji, bud  
nejak presvedcit ten parser at to nedela nebo coz bude mnohem lepsi, nejak  
to zachytit a vypsat, zkusim nejak vymyslet jak na to.

Vlada

On Thu, 16 Feb 2012 19:38:47 +0100, l-korous  
reply@reply.github.com  
wrote:

**Comment by l-korous** [comment]
2012/2/16 blackvladimir <
reply@reply.github.com

> ono je treba to config.pxi includovat jak na zacatku hlavniho pxd souboru
> tak na zacatku pyx souboru.
> 
> ad "This engine tried to send data to standard output, and therefore it
> was terminated." Zjistil jsem ze to dela xml parser, kdyz je v xml nejaka
> chyba tak ji vypise na standartni chybovy vystup. Reseni je dvoji, bud
> nejak presvedcit ten parser at to nedela nebo coz bude mnohem lepsi, nejak
> to zachytit a vypsat, zkusim nejak vymyslet jak na to.

No, tam jsou vyjimky normalne implementovane pokud se spravne pamatuju,
stacilo by asi +translateException.

Lukas

> Vlada
> 
> On Thu, 16 Feb 2012 19:38:47 +0100, l-korous
> reply@reply.github.com
> wrote:
> 
> > On Thu, Feb 16, 2012 at 7:30 PM, blackvladimir <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Tak to vypnul luke kdyz neco testoval. Ja jsem to vratil a funguje to
> > > akorat hermes_module pouziva grafiku takze nejde importovat. Konretne je
> > > to PyWinGeom.
> > 
> > Ono je to tim, ze se tam nebere ohled na config.pxi. Nevim proc, ale
> > vyresil jsem to tak, ze pred "import hermes2d" jsem dal "DEF GUI =
> > False",
> > moduly stejne nebudou zadne Viewcka nikdy pouzivat. Ted to ladim u sebe,
> > pak to dam na truckee.
> > 
> > > Dalsi vec je ze hermes pri calculation testu hazi to jak uz si psal s
> > > tim
> > > ze to neco pise na standartni vystup. Me se to nedari reprodukovat u
> > > sebe
> > > ale muzu to zkusit odladit na truckee.
> > 
> > A u Tebe to funguje, jak hermes, tak wrappery aktualni verze?
> > 
> > Lukas
> > 
> > > On Thu, 16 Feb 2012 18:12:41 +0100, l-korous
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > Ja jsem mimo podezreni, protoze ani nevim jak bych to udelal :).
> > > > 
> > > > OK, muzes to poladit a overit tedy jestli jsem spravne nainstaloval
> > > > hermes
> > > > & wrappery do pythonroot.tar.gz, ze se to importne?
> > > > 
> > > > L
> > > > 
> > > > On Thu, Feb 16, 2012 at 6:09 PM, blackvladimir <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > Aha on nekdo vypnul na nodech zabezpeceni pythonu. Nevim jaky mel k
> > > > > tomu
> > > > > duvod.
> > > > > 
> > > > > On Thu, 16 Feb 2012 18:00:22 +0100, l-korous
> > > > > reply@reply.github.com
> > > > > wrote:
> > > > > 
> > > > > > OK, no ja jsem ted tedy nainstaloval do pythonroot.tar.gz na
> > > > > > truckee
> > > > > > hermes
> > > > > > s
> > > > > > set(H2D_WITH_GLUT NO) a wrappery s DEF GUI = False
> > > > > > a stejne dostavam tu chybu.
> > > > > > 
> > > > > > A dal jsem si praci zjistit proc - je to tim, ze se bere hermes ze
> > > > > > systemu
> > > > > > (z femhubu) a nikoliv z pythonroot.tar.gz.
> > > > > > 
> > > > > > Jak to overit:
> > > > > > - worksheet se mi evaluoval na lenovu (myslim ze kdyz jsem
> > > > > >   updatoval
> > > > > >   nclab,
> > > > > >   tak to byla jedina noda, kde update prosel uspesne, to jen rikam
> > > > > >   kdybys
> > > > > >   na
> > > > > >   to narazil)
> > > > > > - no a kdyz jsem tu hlasku
> > > > > >   "ImportError: libGLEW.so.1.6: cannot open shared object file: No
> > > > > >   such
> > > > > >   file
> > > > > >   or
> > > > > >   directory"
> > > > > >   dostal, tak jsem pokusne smazal hermes z femhubu na lenovu, a
> > > > > >   dostal
> > > > > >   jsem
> > > > > >   hlasku o chybejicim hermesu.
> > > > > > 
> > > > > > Lukas
> > > > > > 
> > > > > > On Thu, Feb 16, 2012 at 10:23 AM, blackvladimir <
> > > > > > reply@reply.github.com
> > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > Ano, zkousel jsem to bez nainstalovaneho GLEW a fungovalo to.
> > > > > > > 
> > > > > > > v Hermesu v CMake.vars
> > > > > > > 
> > > > > > > set(H2D_WITH_GLUT NO)
> > > > > > > 
> > > > > > > a ve wraperech v config.pxi
> > > > > > > 
> > > > > > > DEF GUI = False
> > > > > > > 
> > > > > > > Vlada
> > > > > > > 
> > > > > > > On Wed, 15 Feb 2012 19:00:16 +0100, l-korous
> > > > > > > reply@reply.github.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Ahoj,
> > > > > > > > 
> > > > > > > > ma tohle znamenat ze bych nemel dostavat hlasky typu:
> > > > > > > > "ImportError:
> > > > > > > > libGLEW.so.1.6: cannot open shared object file: No such file or
> > > > > > > > directory"?
> > > > > > > > 
> > > > > > > > Nebo to prestane az kdyz setnu NO_GLUT v hermesu?
> > > > > > > > 
> > > > > > > > Lukas
> > > > > > > > 
> > > > > > > > On Thu, Feb 9, 2012 at 2:29 PM, blackvladimir <
> > > > > > > > reply@reply.github.com
> > > > > > > > 
> > > > > > > > > wrote:
> > > > > > > > > 
> > > > > > > > > in server instalation we doesn't need gui.
> > > > > > > > > 
> > > > > > > > > You can merge this Pull Request by running:
> > > > > > > > > 
> > > > > > > > >  git pull https://github.com/blackvladimir/hermes-pythonmaster
> > > > > > > > > 
> > > > > > > > > Or you can view, comment on it, or merge it online at:
> > > > > > > > > 
> > > > > > > > >  https://github.com/hpfem/hermes-python/pull/24
> > > > > > > > > 
> > > > > > > > > -- Commit Summary --
> > > > > > > > > - gui can be disabled
> > > > > > > > > 
> > > > > > > > > -- File Changes --
> > > > > > > > > 
> > > > > > > > > A config.pxi (1)
> > > > > > > > > M hermes2d/hermes2d.pxd (21)
> > > > > > > > > M hermes2d/hermes2d.pyx (22)
> > > > > > > > > M hermes2d/setup.py (1)
> > > > > > > > > 
> > > > > > > > > -- Patch Links --
> > > > > > > > > 
> > > > > > > > >  https://github.com/hpfem/hermes-python/pull/24.patch
> > > > > > > > >  https://github.com/hpfem/hermes-python/pull/24.diff
> > > > > > > > > 
> > > > > > > > > ---
> > > > > > > > > 
> > > > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > > > https://github.com/hpfem/hermes-python/pull/24
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > 
> > > > > > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-3997422
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-4004832
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hpfem/hermes-python/pull/24#issuecomment-4006352
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hpfem/hermes-python/pull/24#issuecomment-4006660

## 

_Lukas Korous_

**Pull request merged**
