### PR TITLE
first simple wrapper

### PR DESCRIPTION
**Pull request by blackvladimir**
simple wrapper form mesh reader
file structure of wrappers mirrors hermes structure

### CODE REVIEW

**Comment by l-korous** [comment]
Hazi mi to errory (na windowsech):

d:\hpfem\hermes\l-korous\hermes-python\hermes_common>python setup.py build_ext -
-inplace --include-dirs="..\hermes/hermes_common/include:..\hermes/hermes2d/incl
ude" --library-dirs="..\hermes/hermes_common" -c mingw32
running build_ext
skipping 'hermes_common.cpp' Cython extension (up-to-date)
building 'hermes_common' extension
c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall -I..\hermes/
hermes_common/include:..\hermes/hermes2d/include "-Ic:\Program Files (x86)\Pytho
n26\include" "-Ic:\Program Files (x86)\Python26\PC" -c hermes_common.cpp -o buil
d\temp.win32-2.6\Release\hermes_common.o
writing build\temp.win32-2.6\Release\hermes_common.def
c:\Program Files (x86)\MinGW\bin\g++.exe -mno-cygwin -mdll -static --entry _DllM
ain@12 --output-lib build\temp.win32-2.6\Release\libhermes_common.a --def build\
temp.win32-2.6\Release\hermes_common.def -s build\temp.win32-2.6\Release\hermes_
common.o -L..\hermes/hermes_common "-Lc:\Program Files (x86)\Python26\libs" "-Lc
:\Program Files (x86)\Python26\PCbuild" -lhermes_common -lpython26 -lmsvcr90 -o
d:\hpfem\hermes\l-korous\hermes-python\hermes_common\hermes_common.pyd
c:/program files (x86)/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bi
n/ld.exe: cannot find -lhermes_common
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1

d:\hpfem\hermes\l-korous\hermes-python\hermes_common>cd ..\hermes2d

d:\hpfem\hermes\l-korous\hermes-python\hermes2d>python setup.py build_ext --inpl
ace --include-dirs="..\hermes/hermes_common/include:..\hermes/hermes2d/include"
--library-dirs="..\hermes/hermes2d" -c mingw32
running build_ext
skipping 'hermes2d.cpp' Cython extension (up-to-date)
building 'hermes2d' extension
c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall -I..\hermes/
hermes_common/include:..\hermes/hermes2d/include "-Ic:\Program Files (x86)\Pytho
n26\include" "-Ic:\Program Files (x86)\Python26\PC" -c hermes2d.cpp -o build\tem
p.win32-2.6\Release\hermes2d.o
hermes2d.cpp:223:23: fatal error: mesh/mesh.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by blackvladimir** [comment]
Problem je v nastaveni cest. Ted jak na to koukam tak masb  .bat
skriptu normalni lomitka i zpetna to nevim jestli mingw zvlada. A
dalsi vec je ze to asi nebude fungovat s relativni adresou jako
bazovou pro hermes, ten vlastni preklad se dela v adresari
hermes2d/build takze je treba zadat spravny pocet dvojtecek.

Vlada

On Tue, Oct 4, 2011 at 4:27 PM, l-korous
reply@reply.github.com
wrote:

**Comment by l-korous** [comment]
On Tue, Oct 4, 2011 at 5:18 PM, blackvladimir <
reply@reply.github.com>wrote:

> Problem je v nastaveni cest. Ted jak na to koukam tak masb  .bat
> skriptu normalni lomitka i zpetna to nevim jestli mingw zvlada.

Mel by, ale taky jsem to zkousel dat vsude windowsi a to same.

> A
> dalsi vec je ze to asi nebude fungovat s relativni adresou jako
> bazovou pro hermes

Take jsem zkousel

> , ten vlastni preklad se dela v adresari
> hermes2d/build takze je treba zadat spravny pocet dvojtecek.

Neni ten skript v batch filu je stejny jako ten shell skript co se tyka
dvojtecek?

L

**Comment by blackvladimir** [comment]
Spatne jsem se vyjadril, dvojteckama jsem myslel ".." v relativni
ceste. Nevim jak jsou behem prekladu nastaveny cesty takze je rozhodne
lepsi pouzivat absolutni. Cesta : ..\hermes urcite fungovat nebude.

Posli mi kdyz tak vypis s absolutni cestou

On Tue, Oct 4, 2011 at 5:29 PM, l-korous
reply@reply.github.com
wrote:

> On Tue, Oct 4, 2011 at 5:18 PM, blackvladimir <

**Comment by l-korous** [comment]
To jsem pochopil. Moje pointa byla, ze co se tyka tech dvou skriptu, tak
krome te cesty co tam zadavam jsou identicke, a Tobe to chodi. Tady je vypis
s plnou cestou:

d:\hpfem\hermes\l-korous\hermes-python>wrappers_generate.bat

d:\hpfem\hermes\l-korous\hermes-python>set
HERMES_DIR=d:\hpfem\hermes\l-korous\h
ermes\hermes2d

d:\hpfem\hermes\l-korous\hermes-python>cd hermes_common

d:\hpfem\hermes\l-korous\hermes-python\hermes_common>python setup.py
build_ext -
-inplace
--include-dirs="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common\
include:d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d\include"
--library-dir
s="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common" -c mingw32
running build_ext
skipping 'hermes_common.cpp' Cython extension (up-to-date)
building 'hermes_common' extension
c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall
-Id:\hpfem\h
ermes\l-korous\hermes\hermes2d\hermes_common\include:d:\hpfem\hermes\l-korous\he
rmes\hermes2d\hermes2d\include "-Ic:\Program Files (x86)\Python26\include"
"-Ic:
\Program Files (x86)\Python26\PC" -c hermes_common.cpp -o
build\temp.win32-2.6\R
elease\hermes_common.o
writing build\temp.win32-2.6\Release\hermes_common.def
c:\Program Files (x86)\MinGW\bin\g++.exe -mno-cygwin -mdll -static --entry
_DllM
ain@12 --output-lib build\temp.win32-2.6\Release\libhermes_common.a --def
build\
temp.win32-2.6\Release\hermes_common.def -s
build\temp.win32-2.6\Release\hermes_
common.o -Ld:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common
"-Lc:\Program
Files (x86)\Python26\libs" "-Lc:\Program Files (x86)\Python26\PCbuild"
-lhermes_
common -lpython26 -lmsvcr90 -o
d:\hpfem\hermes\l-korous\hermes-python\hermes_com
mon\hermes_common.pyd
c:/program files
(x86)/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bi
n/ld.exe: cannot find -lhermes_common
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1

d:\hpfem\hermes\l-korous\hermes-python\hermes_common>cd ..\hermes2d

d:\hpfem\hermes\l-korous\hermes-python\hermes2d>python setup.py build_ext
--inpl
ace
--include-dirs="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common\inclu
de:d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d\include"
--library-dirs="d:
\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d" -c mingw32
running build_ext
skipping 'hermes2d.cpp' Cython extension (up-to-date)
building 'hermes2d' extension
c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall
-Id:\hpfem\h
ermes\l-korous\hermes\hermes2d\hermes_common\include:d:\hpfem\hermes\l-korous\he
rmes\hermes2d\hermes2d\include "-Ic:\Program Files (x86)\Python26\include"
"-Ic:
\Program Files (x86)\Python26\PC" -c hermes2d.cpp -o
build\temp.win32-2.6\Releas
e\hermes2d.o
hermes2d.cpp:223:23: fatal error: mesh/mesh.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

Lukas

**Comment by blackvladimir** [comment]
Ja mingw prilis neznam tak nevim jak pracuje s cestami ale treba
d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common\include:d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d\include

mu asi bude delat problemy (hlavne ty dve dvojtecky kolem d). Co si  
pamatuju tak v mingw bylo mozne zadavat cestu jako /d/hpfem .
a na druhou stranu ve windows se myslim cesty oddeluji strednikem.

On Tue, 04 Oct 2011 18:02:02 +0200, l-korous  
reply@reply.github.com  
wrote:

> To jsem pochopil. Moje pointa byla, ze co se tyka tech dvou skriptu, tak
> krome te cesty co tam zadavam jsou identicke, a Tobe to chodi. Tady je  
> vypis
> s plnou cestou:
> 
> d:\hpfem\hermes\l-korous\hermes-python>wrappers_generate.bat
> 
> d:\hpfem\hermes\l-korous\hermes-python>set
> HERMES_DIR=d:\hpfem\hermes\l-korous\h
> ermes\hermes2d
> 
> d:\hpfem\hermes\l-korous\hermes-python>cd hermes_common
> 
> d:\hpfem\hermes\l-korous\hermes-python\hermes_common>python setup.py
> build_ext -
> -inplace
> --include-dirs="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common\
> include:d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d\include"
> --library-dir
> s="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common" -c mingw32
> running build_ext
> skipping 'hermes_common.cpp' Cython extension (up-to-date)
> building 'hermes_common' extension
> c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall
> -Id:\hpfem\h
> ermes\l-korous\hermes\hermes2d\hermes_common\include:d:\hpfem\hermes\l-korous\he
> rmes\hermes2d\hermes2d\include "-Ic:\Program Files  
> (x86)\Python26\include"
> "-Ic:
> \Program Files (x86)\Python26\PC" -c hermes_common.cpp -o
> build\temp.win32-2.6\R
> elease\hermes_common.o
> writing build\temp.win32-2.6\Release\hermes_common.def
> c:\Program Files (x86)\MinGW\bin\g++.exe -mno-cygwin -mdll -static  
> --entry
> _DllM
> ain@12 --output-lib build\temp.win32-2.6\Release\libhermes_common.a --def
> build\
> temp.win32-2.6\Release\hermes_common.def -s
> build\temp.win32-2.6\Release\hermes_
> common.o -Ld:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common
> "-Lc:\Program
> Files (x86)\Python26\libs" "-Lc:\Program Files (x86)\Python26\PCbuild"
> -lhermes_
> common -lpython26 -lmsvcr90 -o
> d:\hpfem\hermes\l-korous\hermes-python\hermes_com
> mon\hermes_common.pyd
> c:/program files
> (x86)/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bi
> n/ld.exe: cannot find -lhermes_common
> collect2: ld returned 1 exit status
> error: command 'g++' failed with exit status 1
> 
> d:\hpfem\hermes\l-korous\hermes-python\hermes_common>cd ..\hermes2d
> 
> d:\hpfem\hermes\l-korous\hermes-python\hermes2d>python setup.py build_ext
> --inpl
> ace
> --include-dirs="d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes_common\inclu
> de:d:\hpfem\hermes\l-korous\hermes\hermes2d\hermes2d\include"
> --library-dirs="d:
> \hpfem\hermes\l-korous\hermes\hermes2d\hermes2d" -c mingw32
> running build_ext
> skipping 'hermes2d.cpp' Cython extension (up-to-date)
> building 'hermes2d' extension
> c:\Program Files (x86)\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall
> -Id:\hpfem\h
> ermes\l-korous\hermes\hermes2d\hermes_common\include:d:\hpfem\hermes\l-korous\he
> rmes\hermes2d\hermes2d\include "-Ic:\Program Files  
> (x86)\Python26\include"
> "-Ic:
> \Program Files (x86)\Python26\PC" -c hermes2d.cpp -o
> build\temp.win32-2.6\Releas
> e\hermes2d.o
> hermes2d.cpp:223:23: fatal error: mesh/mesh.h: No such file or directory
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> 
> Lukas
> 
> On Tue, Oct 4, 2011 at 5:41 PM, blackvladimir <

**Comment by l-korous** [comment]
Jeste to zkouknu, zatim to pushnu, at muzes pokracovat v praci. Samozrejme v
uplne nejhorsim to proste na windowsech nepujde, ale toho bych se nevzdaval
predcasne.

Lukas

**Comment by l-korous** [comment]
Tak jsem se dostal k tomuhle, bylo to tim strednikem v oddelovani. Nicmene
mam dotaz:

v setup.py (tohle je z hermes_common) je tohle:
...,libraries=["hermes_common"]...

A dostavam chybu, ze ta knihovna neexistuje. Co to znamena tohle? Neni to
linkovani? Pak by mel smysl pouze hermes_common v hermes2d, ne?

A jak jinak pokracujes?

Diky,
Lukas

**Comment by blackvladimir** [comment]
Ahoj,
to je linkovani primo k hermesu ty dva pythoni wrappery navzajem
slinkujou az pri nacteni v pythonu. hermes_common znamena ze se to
linkuje k libhermes_common.so (nebo dll).

Jinak me se podarilo odhalit v cythonu chybu na kterou kupodivu jeste
nikdo nenarazil. Problem je ze ta chyba je v tom co zrovna pouzivame
takze ted vymyslim jak to nejak rozume obejit.

odkaz do mailing listu na tu chybu
http://groups.google.com/group/cython-users/browse_thread/thread/2f5faf02b99d85d3

Vlada

2011/10/11 l-korous
reply@reply.github.com:

> Tak jsem se dostal k tomuhle, bylo to tim strednikem v oddelovani. Nicmene
> mam dotaz:
> 
> v setup.py (tohle je z hermes_common) je tohle:
> ...,libraries=["hermes_common"]...
> 
> A dostavam chybu, ze ta knihovna neexistuje. Co to znamena tohle? Neni to
> linkovani? Pak by mel smysl pouze hermes_common v hermes2d, ne?
> 
> A jak jinak pokracujes?
> 
> Diky,
> Lukas
>

**Comment by l-korous** [comment]
2011/10/11 blackvladimir <
reply@reply.github.com>

> Ahoj,
> to je linkovani primo k hermesu ty dva pythoni wrappery navzajem
> slinkujou az pri nacteni v pythonu. hermes_common znamena ze se to
> linkuje k libhermes_common.so (nebo dll).

Aha. No tak to je problem ze to i na windowsech hleda "lhermes_common", melo
by to hledat "hermes_common.lib" (k .dll se na windows primo nelinkuje).
Pokusim se na to prijit.

Lukas

> Jinak me se podarilo odhalit v cythonu chybu na kterou kupodivu jeste
> nikdo nenarazil. Problem je ze ta chyba je v tom co zrovna pouzivame
> takze ted vymyslim jak to nejak rozume obejit.
> 
> odkaz do mailing listu na tu chybu
> 
> http://groups.google.com/group/cython-users/browse_thread/thread/2f5faf02b99d85d3
> 
> Vlada
> 
> 2011/10/11 l-korous
> reply@reply.github.com:
> 
> > Tak jsem se dostal k tomuhle, bylo to tim strednikem v oddelovani.
> > Nicmene
> > mam dotaz:
> > 
> > v setup.py (tohle je z hermes_common) je tohle:
> > ...,libraries=["hermes_common"]...
> > 
> > A dostavam chybu, ze ta knihovna neexistuje. Co to znamena tohle? Neni to
> > linkovani? Pak by mel smysl pouze hermes_common v hermes2d, ne?
> > 
> > A jak jinak pokracujes?
> > 
> > Diky,
> > Lukas
> > 
> > On Tue, Oct 4, 2011 at 11:34 PM, Lukas Korous <lukas.korous@gmail.com
> > wrote:
> > 
> > > Jeste to zkouknu, zatim to pushnu, at muzes pokracovat v praci.
> > > Samozrejme
> > > v uplne nejhorsim to proste na windowsech nepujde, ale toho bych se
> > > nevzdaval predcasne.
> > > 
> > > Lukas
> > > 
> > > On Tue, Oct 4, 2011 at 7:09 PM, blackvladimir <

**Comment by l-korous** [comment]
Zdravim,

jak pokracujes? Jde to? Docela by me zajimal progress, abych taky vedel jak
to vypada a co muzu delat ja.

Diky,
Lukas

2011/10/11 Lukas Korous lukas.korous@gmail.com

> 2011/10/11 blackvladimir <
> reply@reply.github.com>
> 
> > Ahoj,
> > to je linkovani primo k hermesu ty dva pythoni wrappery navzajem
> > slinkujou az pri nacteni v pythonu. hermes_common znamena ze se to
> > linkuje k libhermes_common.so (nebo dll).
> 
> Aha. No tak to je problem ze to i na windowsech hleda "lhermes_common",
> melo by to hledat "hermes_common.lib" (k .dll se na windows primo
> nelinkuje). Pokusim se na to prijit.
> 
> Lukas
> 
> > Jinak me se podarilo odhalit v cythonu chybu na kterou kupodivu jeste
> > nikdo nenarazil. Problem je ze ta chyba je v tom co zrovna pouzivame
> > takze ted vymyslim jak to nejak rozume obejit.
> > 
> > odkaz do mailing listu na tu chybu
> > 
> > http://groups.google.com/group/cython-users/browse_thread/thread/2f5faf02b99d85d3
> > 
> > Vlada
> > 
> > 2011/10/11 l-korous
> > reply@reply.github.com:
> > 
> > > Tak jsem se dostal k tomuhle, bylo to tim strednikem v oddelovani.
> > > Nicmene
> > > mam dotaz:
> > > 
> > > v setup.py (tohle je z hermes_common) je tohle:
> > > ...,libraries=["hermes_common"]...
> > > 
> > > A dostavam chybu, ze ta knihovna neexistuje. Co to znamena tohle? Neni
> > > to
> > > linkovani? Pak by mel smysl pouze hermes_common v hermes2d, ne?
> > > 
> > > A jak jinak pokracujes?
> > > 
> > > Diky,
> > > Lukas
> > > 
> > > On Tue, Oct 4, 2011 at 11:34 PM, Lukas Korous <lukas.korous@gmail.com
> > > wrote:
> > > 
> > > > Jeste to zkouknu, zatim to pushnu, at muzes pokracovat v praci.
> > > > Samozrejme
> > > > v uplne nejhorsim to proste na windowsech nepujde, ale toho bych se
> > > > nevzdaval predcasne.
> > > > 
> > > > Lukas
> > > > 
> > > > On Tue, Oct 4, 2011 at 7:09 PM, blackvladimir <

**Comment by l-korous** [comment]
Jinak tady je pro inspiraci jak vypadaly wrappery drive:

http://femhub.org/doc/src/hermes2d/tutorial-1.html

Lukas

2011/10/11 Lukas Korous lukas.korous@gmail.com

> Tak jsem se dostal k tomuhle, bylo to tim strednikem v oddelovani. Nicmene
> mam dotaz:
> 
> v setup.py (tohle je z hermes_common) je tohle:
> ...,libraries=["hermes_common"]...
> 
> A dostavam chybu, ze ta knihovna neexistuje. Co to znamena tohle? Neni to
> linkovani? Pak by mel smysl pouze hermes_common v hermes2d, ne?
> 
> A jak jinak pokracujes?
> 
> Diky,
> Lukas
>

**Pull request merged**
